[files]
extend-exclude = [
    "cv_latex/**",
    "src/content/publications/bibliography/papers.bib",
    "src/content/posts/001-secure-nginx-client-certificates.mdx",
    "pnpm-lock.yaml",
    "package-lock.json"
]